item {
    name: "Gao Huyet Rong",
    id: 1,
    display_name: "Gao Huyet Rong"
}
item {
    name: "Gao Lai Sua",
    id: 2,
    display_name: "Gao Lai Sua"
}
item {
    name: "Gao Long Lai",
    id: 3,
    display_name: "Gao Long Lai"
}
item {
    name: "Gao Lut Bac",
    id: 4,
    display_name: "Gao Lut Bac"
}
item {
    name: "Gao Lut Dien Bien",
    id: 5,
    display_name: "Gao Lut Dien Bien"
}
item {
    name: "Gao Lut Do",
    id: 6,
    display_name: "Gao Lut Do"
}
item {
    name: "Gao Lut Trang",
    id: 7,
    display_name: "Gao Lut Trang"
}
item {
    name: "Gao Nep Cam",
    id: 8,
    display_name: "Gao Nep Cam"
}
item {
    name: "Gao Nep Sap",
    id: 9,
    display_name: "Gao Nep Sap"
}
item {
    name: "Gao Ngoc Troi",
    id: 10,
    display_name: "Gao Ngoc Troi"
}
item {
    name: "Gao Tam",
    id: 11,
    display_name: "Gao Tam"
}
item {
    name: "Gao Tam Thom",
    id: 12,
    display_name: "Gao Tam Thom"
}
item {
    name: "Gao Thom Go Cong",
    id: 13,
    display_name: "Gao Thom Go Cong"
}
item {
    name: "Gao Thom My",
    id: 14,
    display_name: "Gao Thom My"
}
item {
    name: "Gao lut",
    id: 15,
    display_name: "Gao lut"
}
